[package]
name = "node-runtime"
version = "2.0.0-alpha.5"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
serde = { version = "1.0.102", optional = true }

# primitives
sp-authority-discovery = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/authority-discovery" }
sp-consensus-babe = { version = "0.8.0-alpha.5", default-features = false, path = "../../../primitives/consensus/babe" }
sp-block-builder = { path = "../../../primitives/block-builder", default-features = false, version = "2.0.0-alpha.5"}
sp-inherents = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/inherents" }
node-primitives = { version = "2.0.0-alpha.5", default-features = false, path = "../primitives" }
sp-offchain = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/offchain" }
sp-core = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/core" }
sp-std = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/std" }
sp-api = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/api" }
sp-runtime = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/runtime" }
sp-staking = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/staking" }
sp-keyring = { version = "2.0.0-alpha.5", optional = true, path = "../../../primitives/keyring" }
sp-session = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/session" }
sp-transaction-pool = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/transaction-pool" }
sp-version = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/version" }

# frame dependencies
frame-executive = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/executive" }
frame-benchmarking = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/benchmarking", optional = true }
frame-support = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/support" }
frame-system = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/system" }
frame-system-rpc-runtime-api = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/system/rpc/runtime-api/" }
pallet-authority-discovery = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/authority-discovery" }
pallet-authorship = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/authorship" }
pallet-babe = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/babe" }
pallet-balances = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/balances" }
pallet-collective = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/collective" }
pallet-contracts = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/contracts" }
pallet-contracts-primitives = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/contracts/common/" }
pallet-contracts-rpc-runtime-api = { version = "0.8.0-alpha.5", default-features = false, path = "../../../frame/contracts/rpc/runtime-api/" }
pallet-democracy = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/democracy" }
pallet-elections-phragmen = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/elections-phragmen" }
pallet-finality-tracker = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/finality-tracker" }
pallet-grandpa = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/grandpa" }
pallet-im-online = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/im-online" }
pallet-indices = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/indices" }
pallet-identity = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/identity" }
pallet-membership = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/membership" }
pallet-offences = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/offences" }
pallet-randomness-collective-flip = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/randomness-collective-flip" }
pallet-recovery = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/recovery" }
pallet-session = { version = "2.0.0-alpha.5", features = ["historical"], path = "../../../frame/session", default-features = false }
pallet-session-benchmarking = { version = "2.0.0-alpha.5", path = "../../../frame/session/benchmarking", default-features = false, optional = true }
pallet-staking = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/staking" }
pallet-staking-reward-curve = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/staking/reward-curve" }
pallet-sudo = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/sudo" }
pallet-society = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/society" }
pallet-timestamp = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/timestamp" }
pallet-treasury = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/treasury" }
pallet-utility = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/utility" }
pallet-transaction-payment = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/transaction-payment" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/transaction-payment/rpc/runtime-api/" }
pallet-vesting = { version = "2.0.0-alpha.5", default-features = false, path = "../../../frame/vesting" }

# full crypto
ed25519-dalek = { version = "1.0.0-pre.3", default-features = false, features = ["u64_backend", "alloc"], optional = true }
blake2-rfc = { version = "0.2.18", default-features = false, optional = true }
tiny-keccak = { version = "2.0.1", features = ["keccak"], optional = true }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false, optional = true }
sha2 = { version = "0.8.0", default-features = false, optional = true }
hex = { version = "0.4", default-features = false, optional = true }
twox-hash = { version = "1.5.0", default-features = false, optional = true }
libsecp256k1 = { version = "0.3.2", default-features = false, features = ["hmac"], optional = true }

sp-runtime-interface = { version = "2.0.0-alpha.5", default-features = false, path = "../../../primitives/runtime-interface" }

[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", path = "../../../utils/wasm-builder-runner" }

[dev-dependencies]
sp-io = { version = "2.0.0-alpha.5", path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
    "full_crypto",
	"sp-authority-discovery/std",
	"sp-runtime-interface/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-membership/std",
	"pallet-identity/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"serde",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-benchmarking/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"sp-version/std",
	"pallet-society/std",
	"pallet-recovery/std",
	"pallet-vesting/std",
	"ed25519-dalek/std",
	"blake2-rfc/std",
	"tiny-keccak",
	"schnorrkel/std",
	"hex/std",
	"sha2/std",
	"twox-hash/std",
	"libsecp256k1/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-session-benchmarking",
	"pallet-staking/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
]
full_crypto = [
	"ed25519-dalek",
	"blake2-rfc",
	"tiny-keccak",
	"schnorrkel",
	"hex",
	"sha2",
	"twox-hash",
	"libsecp256k1",
	"sp-runtime-interface/disable_target_static_assertions",
]
